configfile: "../config/config.yaml"

rule all:
    input:
        expand("../results/00-raw_data/{sample}_1.fastq.gz", sample=config["accession"]),
        expand("../results/00-raw_data/{sample}_2.fastq.gz", sample=config["accession"]),
        # #preprocessing - fastqc-raw-data
        expand("../results/01-preprocessing/01-raw_data-fastqc/{sample}.1_raw_data.html", sample=config["accession"]),
        expand("../results/01-preprocessing/01-raw_data-fastqc/{sample}.1_raw_data_fastqc.zip", sample=config["accession"]),
        expand("../results/01-preprocessing/01-raw_data-fastqc/{sample}.2_raw_data.html", sample=config["accession"]),
        expand("../results/01-preprocessing/01-raw_data-fastqc/{sample}.2_raw_data_fastqc.zip", sample=config["accession"]),
        # #preprocessing - fastqc-cutadapt_output
        expand("../results/01-preprocessing/03-cutadapt_output-fastqc/{sample}.1_cutadapt_output.html", sample=config["accession"]),
        expand("../results/01-preprocessing/03-cutadapt_output-fastqc/{sample}.1_cutadapt_output_fastqc.zip", sample=config["accession"]),
        expand("../results/01-preprocessing/03-cutadapt_output-fastqc/{sample}.2_cutadapt_output.html", sample=config["accession"]),
        expand("../results/01-preprocessing/03-cutadapt_output-fastqc/{sample}.2_cutadapt_output_fastqc.zip", sample=config["accession"]),
        # #preprocessing - kneaddata-database
        expand("../resources/human_database"),
        #preprocessing - fastqc-kneaddata
        expand("../results/01-preprocessing/05-kneaddata_output-fastqc/{sample}.1_kneaddata_output.html", sample=config["accession"]),
        expand("../results/01-preprocessing/05-kneaddata_output-fastqc/{sample}.1_kneaddata_output_fastqc.zip", sample=config["accession"]),
        expand("../results/01-preprocessing/05-kneaddata_output-fastqc/{sample}.2_kneaddata_output.html", sample=config["accession"]),
        expand("../results/01-preprocessing/05-kneaddata_output-fastqc/{sample}.2_kneaddata_output_fastqc.zip", sample=config["accession"]),
        #pydamage
        # expand("../results/04-aDNA_authentication/pydamage/{sample}_pydamage/{sample}_pydamage_filtered_results.csv", sample=config["accession"]),
        # expand("../results/04-aDNA_authentication/pydamage/{sample}_pydamage/pydamage_results.csv", sample=config["accession"])
        #final
        expand("../results/02-assembly/{sample}/{sample}_scaffolds_filtered_4k_20cov.fasta", sample=config["accession"]),


include: "rules/downloads.smk"
include: "rules/preprocessing.smk"
include: "rules/assembly.smk"
#inlcude: "rules/aDNA_authentication.smk"
